sudo apt-get update
sudo apt-get upgrade

sudo dpkg-reconfigure --priority=low unattended-upgrades

# in case of locale problems ``` perl: warning: Setting locale failed.```
sudo locale-gen en_US.UTF-8 cs_CZ.UTF-8
sudo dpkg-reconfigure locales

#basic
sudo apt-get install htop iotop

#git install
sudo apt-get install -y git-core

sudo apt-get install -y build-essential zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev libncurses5-dev libffi-dev curl openssh-server redis-server checkinstall libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev logrotate

# because of json gem:
sudo apt-get install libgmp-dev libgmp3-dev

# because of pg gem:
sudo apt-get install libpq-dev

sudo apt-get install postgresql
sudo apt-get install postgresql-9.3-postgis-2.1 postgresql-9.3-postgis-2.1-scripts postgis
sudo apt-get install libgdal1-dev #optionaly for raser support

sudo -u postgres psql <<EOF
create database local_administration_model_production;
create role deployer with createdb login password 'serepes';
GRANT ALL PRIVILEGES ON DATABASE local_administration_model_production TO deployer;
\c local_administration_model_production
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
EOF

echo "listen_addresses = '*'" >> /etc/postgresql/9.3/main/postgresql.conf

cat >>/etc/postgresql/9.3/main/pg_hba.conf <<EOF
host    all             all             81.2.251.113/32            md5
host    all             all             .mapasamospravy.cz            md5
host    all             all             mapasamospravy.cz            md5
host    all             all             luksrock.cz            md5
EOF


cat > /etc/iptables.rules  <<EOF
# Generated by iptables-save v1.4.21 on Tue Apr 26 10:12:58 2016
*filter
:INPUT ACCEPT [102:9512]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [74:12990]
-A INPUT -s 127.0.0.1/32 -p tcp -m tcp --dport 5432 -j ACCEPT
-A INPUT -s 81.2.242.238/32 -p tcp -m tcp --dport 5432 -j ACCEPT
-A INPUT -s 81.2.243.51/32 -p tcp -m tcp --dport 5432 -j ACCEPT
-A INPUT -s 84.42.154.30/32 -p tcp -m tcp --dport 5432 -j ACCEPT
-A INPUT -s 81.2.251.113/32 -p tcp -m tcp --dport 5432 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5432 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Tue Apr 26 10:12:58 2016
EOF
echo "    pre-up iptables-restore < /etc/iptables.rules" >> /etc/network/interfaces

# on the server: 
# 1. rake db:create rake db:migrate in local_administration_model project
# 2. rake db:migrate in las_control project

pg_restore -h localhost -U deployer -W -a -d local_administration_model_production local_administration_model_DB.dump

# restore ruian db:

# 1. pg_dump -d ruian -U ob -t 'rn_*' -T 'rn_parcela' -T rn_stavebni_objekt -T rn_adresni_misto -T rn_zpusob_ochrany_pozemku -T rn_bonit_dily_parcel -T rn_zsj -Fc > ruian.dump
sudo -u postgres psql <<EOF
create database "ruian";
create role ob with createdb login password 'ob';
GRANT ALL PRIVILEGES ON DATABASE ruian TO ob;
\c ruian
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
EOF

pg_restore -h localhost -U ob -W -d ruian ruian.dump

cat >>/etc/postgresql/9.3/main/postgresql.conf <<EOF
# Because of `PG::UnableToSend: SSL SYSCALL error: EOF detected` error
# see
#   https://github.com/rails/rails/issues/20411
#   https://github.com/rails/rails/issues/12867
#   http://stackoverflow.com/questions/19802233/heroku-sidekiq-activerecordstatementinvalid-pgunabletosend-ssl-syscall
tcp_keepalives_idle = 60
tcp_keepalives_interval = 60
tcp_keepalives_count = 9  # e.g. 9
EOF
