source 'https://rubygems.org'

ruby '2.3.0'
gem 'dotenv'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'rspec-rails', '~> 3.4'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'ruian_model',                path: '../ruian_model'
gem 'local_administration_model', path: '../local_administration_model'
gem 'sidekiq',                    '~> 4.0'

gem 'rails-i18n'
gem 'haml'
gem 'devise'
gem 'cancancan', '~> 1.10'
gem 'settingslogic', '~> 2.0'
gem 'simple_form', '~> 3.2'
gem 'elasticsearch-rails'
gem 'select2-rails', '~> 3.5.2' #select2 v.4 see https://select2.github.io/announcements-4.0.html#removed-initselection

gem 'rack-cache', :require => 'rack/cache' # dragonfly caching
gem 'dragonfly', '~> 1.0'

#view generated by: rails g kaminari:views bootstrap3
gem 'kaminari', '~> 0.16.3'

gem 'ransack', '~> 1.7'
gem 'font-awesome-sass', '~> 4.5.0'

# TODO: remove `github` as soon as pullrequrest #28 will be merged
gem 'kaminari-i18n', github: 'lksv/kaminari-i18n'

# currently last release of devise-i18n is 0.12.1 and it does not contains any
#  views (current commit is f26a02454f5acfc2c39d91efcfd75b9068078e6f).
gem 'devise-i18n', github: 'tigrish/devise-i18n', branch: 'master'

gem 'bootstrap-sass', '~> 3.3.6'

gem 'jquery-ui-rails', '~> 4.2.1'
gem 'momentjs-rails'

# The bootstrap and devise layout was generated by this gem
# gem 'rails_layout'

group :production do
  #gem 'puma'
end
gem "sentry-raven"
gem 'rollbar', '~> 2.8.3'
gem 'rake'
